services:
  django:
    build:
      context: ..
      dockerfile: ./services/django/Dockerfile
    restart: unless-stopped
    expose:
      - ${DJANGO_PORT:-8000}
    volumes:
      - ../django:/app
      - /app/node_modules
    env_file:
      - ../compose/.env
    environment:
      VIRTUAL_HOST: "${DJANGO_VIRTUAL_HOST:-${VIRTUAL_HOST:-localhost,127.0.0.1}}"
      VIRTUAL_PATH: "${DJANGO_VIRTUAL_PATH:?Django virtual path not set}"
      VIRTUAL_PROTO: "${DJANGO_VIRTUAL_PROTO:-${VIRTUAL_PROTO:-http}}"
      VIRTUAL_PORT: ${DJANGO_PORT:-8000}
    command:
      [
        "/usr/local/bin/gunicorn",
        "sdo.wsgi",
        "--bind",
        "0.0.0.0:8000",
        "--chdir=/app",
        "--timeout",
        "180",
        "--forwarded-allow-ips=0.0.0.0",
      ]
    depends_on:
      postgres:
        condition: service_healthy
