services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    expose:
      - ${NGINX_PORT:-8001}
    volumes:
      - ../xmod/webapp/ROOT/_a:/usr/share/nginx/_a:ro
      - ../xmod/webapp/ROOT/images:/usr/share/nginx/images:ro
    environment:
      VIRTUAL_HOST: "${NGINX_VIRTUAL_HOST:-${VIRTUAL_HOST:-localhost,127.0.0.1}}"
      VIRTUAL_PATH: "${NGINX_VIRTUAL_PATH:?nginx virtual path not set}"
      VIRTUAL_PROTO: "${NGINX_VIRTUAL_PROTO:-${VIRTUAL_PROTO:-http}}"
      VIRTUAL_PORT: ${NGINX_PORT:-8001}
