services:
  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: unless-stopped
    expose:
      - ${POSTGRES_PORT:-5432}
    volumes:
      - ../volumes/postgres_data:/var/lib/postgresql/data
      - ../volumes/postgres_backups:/backups
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:?Postgres db not set}
      POSTGRES_USER: ${POSTGRES_USER:?Postgres user not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Postgres user password not set}
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 1s
      timeout: 3s
      retries: 10
