#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate

if [ "$PRODUCTION" = "true" ]; then
    python manage.py collectstatic --no-input
fi

# execute the provided command (from the 'command' property in Docker Compose)
exec "$@"
