#!/usr/bin/perl

use Text::CSV;

#
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
## Name: csv2eats 
## Desc: converts  csv format to django eats fixture 
##
##
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

   if ( @ARGV < 1) {
        die("Usage: csv2eats input ");
   }

   $pathToInput = $ARGV[0];
   $fileToWrite = "schenker.xml";
   $recordCounter = 3;
   my $csv = Text::CSV->new({ binary => 1 });
   open (CSVSRC, "< $pathToInput") or die "Couldn't open $pathToInput for reading: $!\n";
  
  $propAssertionIdCounter = 11;
  $nameIdCounter = 3;
  $namePartCounter = 2;
  $entityNoteCounter = 2;
  
   while (<CSVSRC>) {
   my $line = $_;

     if ($csv->parse($line)) {
        
        my @columns = $csv->fields();        
        my $name = $columns[0];
        
        my @notes = ("is a correspondent: $columns[9]","is a pupil: $columns[10]","$columns[11]","$columns[12]","$columns[13]","$columns[14]","$columns[15]","$columns[16]","$columns[17]");
        my $sizeNotes = @notes;

        my @names = ($columns[0],$columns[1],$columns[2],$columns[3],$columns[4],$columns[5],$columns[6],$columns[7],$columns[8]);
        my $sizeNames = @names;
        
        next if ($name eq 'Sort name' || $name eq '');

        # increment the record counter
        $recordCounter++;
        my $recNumber = sprintf( "%06d", $recordCounter);
    
         my $nameObjects = "";
         my $noteObjects = "";
         my $propAssertions = "";
         
         
       for ($j = 0; $j<$sizeNames; $j++) {
           
        $currName = $names[$j];
        $currName =~ s/^\s*(.*)\s*$/$1/;
        $currName =~ s/&/&amp;/g;
        next if ($currName eq "");
        
        $nameIdCounter++;
        my $objectId = $nameIdCounter;
        
        $isPreferred = ($j ==0) ? 'True':'False';
       
        # First, the main Name Object
        $nameObjects .= "<object pk=\"$objectId\" model=\"eats.name\">\n";
        $nameObjects .= "<field to=\"eats.nametype\" name=\"name_type\" rel=\"ManyToOneRel\">2</field>\n";
        $nameObjects .= "<field to=\"eats.language\" name=\"language\" rel=\"ManyToOneRel\">1</field>\n";
        $nameObjects .= "<field to=\"eats.script\" name=\"script\" rel=\"ManyToOneRel\">1</field>\n";
        
        if ($j != 0) {
        $nameObjects .= "<field type=\"CharField\" name=\"display_form\">$currName</field>\n";
        } else {
       # $nameObjects .= "<field type=\"CharField\" name=\"display_form\"><None/></field>\n";
        }
        
        $nameObjects .= "</object>\n";
        
        # Add the sort name from Ian's spreadsheet to the family namepart.
        if ($j == 0) {
        $namePartCounter++;
        my $partId = $namePartCounter;
        
         $nameObjects .= "<object pk=\"$partId\" model=\"eats.namepart\">\n";
         $nameObjects .= "<field to=\"eats.name\" name=\"name\" rel=\"ManyToOneRel\">$objectId</field>\n";
         $nameObjects .= "<field to=\"eats.nameparttype\" name=\"name_part_type\" rel=\"ManyToOneRel\">1</field>\n";
         $nameObjects .= "<field to=\"eats.language\" name=\"language\" rel=\"ManyToOneRel\">1</field>\n";
         $nameObjects .= "<field to=\"eats.script\" name=\"script\" rel=\"ManyToOneRel\">1</field>\n";
         $nameObjects .= "<field type=\"CharField\" name=\"name_part\">$currName</field>\n</object>\n";
         
        
        }
         
         
       
       
       # Next the search name
       $nameObjects .= "<object pk=\"$objectId\" model=\"eats.searchname\">\n";
           $nameObjects .= "<field to=\"eats.entity\" name=\"entity\" rel=\"ManyToOneRel\">$recordCounter</field>\n";
           $nameObjects .= "<field to=\"eats.name\" name=\"name\" rel=\"ManyToOneRel\">$recordCounter</field>\n";
           $nameObjects .= "<field type=\"CharField\" name=\"name_form\">$currName</field>\n";
           $nameObjects .= "</object>\n";
       
       # Finally, the corresponding property Assertion
       
       $propAssertionIdCounter++;
       $propId = $propAssertionIdCounter;
       
           $nameObjects .=  "<object pk=\"$propId\" model=\"eats.propertyassertion\">\n";
            $nameObjects .=  "<field to=\"eats.entity\" name=\"entity\" rel=\"ManyToOneRel\">$recordCounter</field>\n";
            $nameObjects .=  "<field to=\"eats.authorityrecord\" name=\"authority_record\" rel=\"ManyToOneRel\">$recordCounter</field>\n";
            $nameObjects .=  "<field type=\"DateField\" name=\"authority_record_checked\"><None/></field>\n";
            $nameObjects .=  "<field to=\"eats.existence\" name=\"existence\" rel=\"ManyToOneRel\"><None/></field>\n";
            $nameObjects .= "<field to=\"eats.entitytype\" name=\"entity_type\" rel=\"ManyToOneRel\"><None/></field>\n";
           $nameObjects .= "<field to=\"eats.name\" name=\"name\" rel=\"ManyToOneRel\">$objectId</field>\n";
             $nameObjects .= "<field to=\"eats.entityrelationship\" name=\"entity_relationship\" rel=\"ManyToOneRel\"><None/></field>\n";
            $nameObjects .= "<field to=\"eats.namerelationship\" name=\"name_relationship\" rel=\"ManyToOneRel\"><None/></field>\n";
            $nameObjects .= "<field to=\"eats.entitynote\" name=\"note\" rel=\"ManyToOneRel\"><None/></field>\n";
            $nameObjects .= "<field to=\"eats.entityreference\" name=\"reference\" rel=\"ManyToOneRel\"><None/></field>\n";
            $nameObjects .= "<field to=\"eats.genericproperty\" name=\"generic_property\" rel=\"ManyToOneRel\"><None/></field>\n";
            $nameObjects .= "<field type=\"BooleanField\" name=\"is_preferred\">$isPreferred</field>\n";
           $nameObjects .= "</object>";
             
       
       }
       
       
       $entityNoteCounter++;
       $noteId = $entityNoteCounter;
        
        $noteObjects .= "<object pk=\"$noteId\" model=\"eats.entitynote\">";
         $noteObjects .= "<field type=\"TextField\" name=\"note\">";
      
     
         $correspondent = $columns[9];
         $correspondent =~ s/^\s*(.*)\s*$/$1/;
         $pupil = $columns[10];
         $pupil =~ s/^\s*(.*)\s*$/$1/;
         $profile = $columns[11];
         $profile =~ s/^\s*(.*)\s*$/$1/;
         
         @roles = ("$columns[12]","$columns[13]","$columns[14]","$columns[15]","$columns[16]","$columns[17]");
         
        if ($correspondent ne "") { $noteObjects .= "-is a correspondent-\n"; }
          
          if ($pupil ne "") { $noteObjects .= "-is a pupil-\n"; }
          
          if ($profile ne "") { $noteObjects .= "-profile exists-\n"; }
          
                    
          for ($k = 0; $k < @roles; $k++) {
          
          $thisRole = $roles[$k];
          $thisRole =~ s/^\s*(.*)\s*$/$1/;
          
          next if($thisRole eq "");
          
          $noteObjects .= "-$thisRole-";
           
          }
       
         $noteObjects .="\n</field>";
         $noteObjects .="<field type=\"BooleanField\" name=\"is_internal\">0</field>\n</object>";
        
       
       $propAssertionIdCounter++;
       
       $noteObjects .=  "<object pk=\"$propAssertionIdCounter\" model=\"eats.propertyassertion\">\n";
        $noteObjects .=  "<field to=\"eats.entity\" name=\"entity\" rel=\"ManyToOneRel\">$recordCounter</field>\n";
        $noteObjects .=  "<field to=\"eats.authorityrecord\" name=\"authority_record\" rel=\"ManyToOneRel\">$recordCounter</field>\n";
        $noteObjects .=  "<field type=\"DateField\" name=\"authority_record_checked\"><None/></field>\n";
        $noteObjects .=  "<field to=\"eats.existence\" name=\"existence\" rel=\"ManyToOneRel\"><None/></field>\n";
        $noteObjects .= "<field to=\"eats.entitytype\" name=\"entity_type\" rel=\"ManyToOneRel\"><None/></field>\n";
        $noteObjects .= "<field to=\"eats.name\" name=\"name\" rel=\"ManyToOneRel\"><None/></field>\n";
        $noteObjects .= "<field to=\"eats.entityrelationship\" name=\"entity_relationship\" rel=\"ManyToOneRel\"><None/></field>\n";
        $noteObjects .= "<field to=\"eats.namerelationship\" name=\"name_relationship\" rel=\"ManyToOneRel\"><None/></field>\n";
        $noteObjects .= "<field to=\"eats.entitynote\" name=\"note\" rel=\"ManyToOneRel\">$noteId</field>\n";
        $noteObjects .= "<field to=\"eats.entityreference\" name=\"reference\" rel=\"ManyToOneRel\"><None/></field>\n";
        $noteObjects .= "<field to=\"eats.genericproperty\" name=\"generic_property\" rel=\"ManyToOneRel\"><None/></field>\n";
        $noteObjects .= "<field type=\"BooleanField\" name=\"is_preferred\">True</field>\n";
        $noteObjects .= "</object>";
        
      
            
        for ($i = 0; $i <2; $i++) {
                                    
            $propAssertionIdCounter++;
            my $objectId = $propAssertionIdCounter;
           
            $propAssertions .=  "<object pk=\"$objectId\" model=\"eats.propertyassertion\">\n";
            $propAssertions .=  "<field to=\"eats.entity\" name=\"entity\" rel=\"ManyToOneRel\">$recordCounter</field>\n";
            $propAssertions .=  "<field to=\"eats.authorityrecord\" name=\"authority_record\" rel=\"ManyToOneRel\">$recordCounter</field>\n";
            $propAssertions .=  "<field type=\"DateField\" name=\"authority_record_checked\"><None/></field>\n";
            $propAssertions .=  "<field to=\"eats.existence\" name=\"existence\" rel=\"ManyToOneRel\">\n";
                
            if ($i == 0) {
                $propAssertions .= "$recordCounter</field>";
            }else {
                $propAssertions .= "<None/></field>";
            }    
            
            $propAssertions .= "<field to=\"eats.entitytype\" name=\"entity_type\" rel=\"ManyToOneRel\">\n";
            
            if ($i ==1) {
                $propAssertions .= "$recordCounter</field>\n";
            
            } else {
            $propAssertions .= "<None/></field>\n";
            }
            
            $propAssertions .=  "<field to=\"eats.entityrelationship\" name=\"entity_relationship\" rel=\"ManyToOneRel\"><None/></field>\n";
            $propAssertions .=  "<field to=\"eats.namerelationship\" name=\"name_relationship\" rel=\"ManyToOneRel\"><None/></field>\n";
            $propAssertions .=  "<field to=\"eats.entitynote\" name=\"note\" rel=\"ManyToOneRel\"><None/></field>\n";
            $propAssertions .=  "<field to=\"eats.entityreference\" name=\"reference\" rel=\"ManyToOneRel\"><None/></field>\n";
            $propAssertions .=  "<field to=\"eats.genericproperty\" name=\"generic_property\" rel=\"ManyToOneRel\"><None/></field>\n";
            $propAssertions .=  "<field type=\"BooleanField\" name=\"is_preferred\">True</field>\n";
            
            $propAssertions .= "</object>";
                
       }

    
    
  


print <<END;
 <object pk="$recordCounter" model="eats.authorityrecord">
        <field to="eats.authority" name="authority" rel="ManyToOneRel">1</field>
        <field type="CharField" name="authority_system_id">n-$recNumber</field>
        <field type="BooleanField" name="is_complete_id">1</field>
        <field type="CharField" name="authority_system_url">n-$recNumber.html</field>
        <field type="BooleanField" name="is_complete_url">0</field>
    </object>
    <object pk="$recordCounter" model="eats.entity"/>


    <object pk="$recordCounter" model="eats.entitytype">
        <field to="eats.entitytypelist" name="entity_type" rel="ManyToOneRel">1</field>
    </object>

    <object pk="$recordCounter" model="eats.existence"/>

    
            
    <!-- Write the Name Objects for each entity -->
     $nameObjects
     
     <!-- Write the Note Objects for each entity -->
         
     $noteObjects
            
    <!-- Three property assertions for each entity to be added: one to register the existence, one to register the association of the name, and one to register the entity type -->

     $propAssertions
     
   
END
     
     } else {
       print "WARN: trouble parsing $line\n";
     }
   }
  close (CSVSRC); 
  
  sub makePropertyAssertions {
  
 
       return $propertyAssertion;
  
  }
