#!/usr/bin/perl
#
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
## Name: mt2xml 
## Desc: converts  movable type format to baseline xml
##
##
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

   if ( @ARGV < 1) {
        die("Usage: mv2xml input ");
   }

   $pathToInput = $ARGV[0];
   $fileToWrite = "schenker.xml";

   open (MTSRC, "< $pathToInput") or die "Couldn't open $pathToInput for reading: $!\n";

   #open (XMLOUT, "> $fileToWrite") or die "Couldn't open $fileToWrite for writing: $! \n";

   print "<recordCollection xmlns:tei=\"http://www.tei-c.org/ns/1.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns=\"http://www.cch.kcl.ac.uk/schenker\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n";   
 
   while (<MTSRC>) {

   next if (/^STATUS:/);
   next if (/^ALLOW/);
   next if (/^CONVERT BREAKS:/);

   # temporary (to work around ill-formed output);
                     

 

   # Structural markup
   s/^AUTHOR: ianbent/<record>\n<dc:source>Movable Type Export<\/dc:source>\n/;
   s/^TITLE:(.*)$/<dc:title>$1<\/dc:title>\n/;
   s/^PRIMARY CATEGORY:(.*)/<dc:subject>primary cat: $1<\/dc:subject>\n/;
   s/^CATEGORY:(.*)/<dc:subject>cat: $1<\/dc:subject>\n/;
   s/^DATE:(.*)$/<dc:date>$1<\/dc:date>\n/;
   s/^BODY:(.*)/\n<tei:transcription>\n/;
   s/^EXTENDED BODY:/<\/tei:transcription>\n<tei:translation>\n/;
   s/^EXCERPT:/<\/tei:translation>\n<notes>\n/;
   s/^\*FOOTNOTES:\*/\n<!-- FOOTNOTES -->/;
   s/^\*FOOTNOTES\*/\n<!-- FOOTNOTES -->/;
   s/^\*COMMENTARY:\*/\n<!-- COMMENTARY -->/;
   s/^\*SUMMARY:\*/\n<!-- SUMMARY -->/;
   s/^\*SUMMARY\*/\n<!-- SUMMARY -->/;
   s/^\*Sender address:\*(.*)/<dc:contributor>sender: $1<\/dc:contributor>/;
   s/^\*Recipient address:\*(.*)/<dc:contributor>recipient: $1<\/dc:contributor>/;
   s/^\*Format:\*(.*)/<dc:format>$1<\/dc:format>/;
   s/^©*(.*)/<dc:rights>© $1<\/dc:rights>/;
   s/^(fn\d{1,3})\.(.*)/<tei:note n=\"$1">$2<\/tei:note>/;

   s/^KEYWORDS:/\n<dc:subject>/;

   # Inline markup
   s/<u>/<!-- was: u elem in MT --><tei:hi rend="underline">/g;
   s/<\/u>/<\/tei:hi>/g;
   s/<em>/<!-- was: em elem in MT --><tei:hi rend="italic">/g;
   s/<\/em>/<\/tei:hi>/g;
   s/<i>/<!-- was: i elem in MT --><tei:hi rend="italic">/g;
   s/<\/i>/<\/tei:hi>/g;
   s/<strong>/<tei:hi rend="bold">/g;
   s/<\/strong>/<\/tei:hi>/g;
   s/<a/<!-- was: a elem in MT --><tei:ref/g;
   s/href="/target="/g;
   s/<\/a>/<\/tei:ref>/g;


   # Tags with no clear equivalent (i.e. for removal)
   s/<small>/<!-- start: small elem in MT -->/g;
   s/<\/small>/<!-- end: small elem in MT -->/g;
   s/<big>/<!-- start: big elem in MT -->/g;
   s/<\/big>/<!-- end: big elem in MT -->/g;
   
   # XML stuff
   s/&/&amp\;/g; 

   
   # Encoding Errors
   s/<\.\//<\//g;

   # Record boundaries
   s/^-----$//;
   s/^--------\n/<\/dc:subject>\n<\/notes>\n<\/record>\n/;


    print $_; 

   }
  print "</recordCollection>\n";
  close (MTSRC); 
